### ISSUE TITLE
Credit assignment?

### ISSUE THREAD

**Issue by AjayTalati** [karpathy/char-rnn#1]
This repo looks a lot like practical 6 from this years Oxford University Machine Learning course,

https://github.com/oxford-cs-ml-2015/practical6

Perhaps you should at least mention that?

**Comment by karpathy** [comment]
I mention on top in the source files. I should probably mention it in the Readme too. Thanks!

**Comment by AjayTalati** [comment]
Yeah I think that's the right thing to do! 

I'd also recommend starting with practical 6, before working through the code in this repo - it's a bit easier to see the basic structure - without the added bells and whistles.

"Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%."
