### ISSUE TITLE
installing Requirements

### ISSUE THREAD

**Issue by Dobiasd** [karpathy/char-rnn#10]
Using a freshly installed Virtualbox with Ubuntu 14.04 I install luarocks

    sudo apt-get install luarocks

Then I call

    sudo luarocks install nngraph

but get

    Error: No results matching query were found.

Do you have any idea on what to do? The installed Lua version is 5.1.5.

**Comment by soumith** [comment]
You shouldn't install luarocks from apt-get, we ship it with the torch
install

**Comment by Dobiasd** [comment]
Great, it worked. Thanks. :+1:
