### ISSUE TITLE
Question: why don't we learn the initial states?

### ISSUE THREAD

**Issue by vzhong** [karpathy/char-rnn#102]
In https://github.com/karpathy/char-rnn/blob/master/train.lua#L288, we have

    -- transfer final state to initial state (BPTT)
    init_state_global = rnn_state[#rnn_state] -- NOTE: I don't think this needs to be a clone, right?

I'm confused about why this line is here. Shouldn't we backprop into the initial states and update them with, say, SGD, instead of setting them to the final `rnn_state`?

**Comment by karpathy** [comment]
That's what you can do if you like, or alternative is to simply start out with all zero, but in this case the entire dataset is a single contiguous string of characters. So the initialization is zero only at VERY beginning for the very first batch, and for every next batch we are carrying over the state from last batch, as we go through the sequence.
