### ISSUE TITLE
About GPU Usage and Monitoring

### ISSUE THREAD

**Issue by loretoparisi** [karpathy/char-rnn#103]
I'm running the rnn on 2.9GHz Intel Core i7/16GB RAM  and Intel HD Graphics 4000 1GB, that is a hardware accelerated OpenGL GPU.
I'm using the option to do calculations on the GPU ( -gpuid 0 ) and using the "OpenGL Driver Monitor" to monitor GPU activities. Which kind of operations are the most intensive performed on the GPU I can monitor?
Thank you.

**Comment by hughperkins** [comment]
Much of the time is spent starting and stopping each kernel unfortunately, in my experience.   Each kernel receives something like 8000floats each time (or maybe a bit more, but not very much).  I was contemplating doing kernel fusion on these kernels, but kind of got side-tracked.  You can see my initial progresson this at https://github.com/torch/nngraph/issues/60

**Comment by loretoparisi** [comment]
Yes, it was OpenCL. Thank you.
