### ISSUE TITLE
Gradient divided by sequence length

### ISSUE THREAD

**Issue by gmkim90** [karpathy/char-rnn#104]
Hi all
I see that gradient in the code is not divided by sequence length.
All of the sequences in the code have fixed length('opt.seq_length'), so minibatch of gradient is proportional to sum of gradients of each sequences. Thus it may not cause any a problem.

Just for clarification, if we train RNN by several sequences with variable length, we need to divide each gradient(of sequence) by sequence length. right?  I am modifying this code and deal with variable sequence length :) 

Thanks !

**Comment by hughperkins** [comment]
This looks a bit like https://github.com/karpathy/char-rnn/issues/70

**Comment by karpathy** [comment]
Thanks @hughperkins , that's correct. Closing.
