### ISSUE TITLE
checkpoints not saving after upgrade to gpu capability

### ISSUE THREAD

**Issue by mwir** [karpathy/char-rnn#107]
Im running char-rnn on Linux Mint 17.2. Everything was working great in CPU mode. 

I got a GPU and installed cuda tools and cutorch and cunn (which involved some wrestling with Torch, basically I had the problem listed in issue #37 and solved it by upgrading cmake)  and char-rnn is suddenly unable to save checkpoints. 

After what looks like a normal, error free training run with gpu 0 enabled, I get the following error:

22/23...	
23/23...	
saving checkpoint to cv/lm_lstm_epoch2.36_1.7848.t7	
/home/mwr/torch/install/bin/luajit: cannot open <cv/lm_lstm_epoch2.36_1.7848.t7> in mode  w at /home/mwr/torch/pkg/torch/lib/TH/THDiskFile.c:484
stack traceback:
	[C]: at 0x7f6baa9c8750
	[C]: in function 'DiskFile'
	/home/mwr/torch/install/share/lua/5.1/torch/File.lua:301: in function 'save'
	train.lua:338: in main chunk
	[C]: in function 'dofile'
	.../mwr/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670
Any idea what might be causing this?

**Comment by hughperkins** [comment]
Just to check, if you do `touch cv/lm_lstm_epoch2.36_1.7848.t7`, what happens?

**Comment by mwir** [comment]
Interestingly the checkpoint appears in the cv file. However, I get a new
error when trying to sample:

mwr@mwr-DX4870 ~/char-rnn $ sudo touch cv/lm_lstm_epoch2.36_1.7848.t7
[sudo] password for mwr:
mwr@mwr-DX4870 ~/char-rnn $ cd cv
mwr@mwr-DX4870 ~/char-rnn/cv $ ls
lm_lstm_epoch2.36_1.7848.t7
mwr@mwr-DX4870 ~/char-rnn/cv $ cd ..
mwr@mwr-DX4870 ~/char-rnn $ th sample.lua cv/lm_lstm_epoch2.36_1.7848.t7
using CUDA on GPU 0...
Make sure that your saved checkpoint was also trained with GPU. If it was
trained with CPU use -gpuid -1 for sampling as well
/home/mwr/torch/install/bin/luajit:
/home/mwr/torch/install/share/lua/5.1/torch/File.lua:199: read error: read
0 blocks instead of 1 at /home/mwr/torch/pkg/torch/lib/TH/THDiskFile.c:302
stack traceback:
    [C]: in function 'readInt'
    /home/mwr/torch/install/share/lua/5.1/torch/File.lua:199: in function
'readObject'
    /home/mwr/torch/install/share/lua/5.1/torch/File.lua:311: in function
'load'
    sample.lua:86: in main chunk
    [C]: in function 'dofile'
    .../mwr/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in
main chunk
    [C]: at 0x00406670

**Comment by hughperkins** [comment]
why are you using `sudo` to `touch`?  I think you should `sudo rm` the checkpoint file, then do `touch`, without sudo, and if that works, then remove the checkpoint file, and try again.

The failure point is doing nothing more complex than open a file, as far as I can tell, so three possibilities seem to be:
- you're out of disk space, so you cannot create any new files
- the file system is corrupted, so you cannot create/delete this file
- the checkpoint file exists, but is owned by root, so you cannot overwrite hte file with non-root user

**Comment by mwir** [comment]
I left out my first attempt at touch:

mwr@mwr-DX4870 ~/char-rnn $ touch cv/lm_lstm_epoch2.36_1.7848.t7
touch: cannot touch ‘cv/lm_lstm_epoch2.36_1.7848.t7’: Permission denied

seeing that is what made me try sudo.

**Comment by hughperkins** [comment]
Ok, so it's a permissions issue apparently.  You need to make sure it is possible to do `touch` using the same user you'r eusing to run char-rnn.  It may be that you ran char-rnn as root earlier, and created the file owned as root, or it may be that the `cv` folder is owned by root.  You could try `sudo chown -R $(whoami):$(whoami) cv`

**Comment by mwir** [comment]
Ok - confirmed, it was just a permissions issue. I opened up permissions on
char-rnn and torch and now everything is up and running. Thank you.

**Comment by hughperkins** [comment]
Cool.  Please mark the issue Closed.
