### ISSUE TITLE
Simple recipe to have another 6% computation speedup  in CUDA mode

### ISSUE THREAD

**Issue by vseledkin** [karpathy/char-rnn#114]
Your input into model is not contiguous in memory. In torch values along first dimension are contiguous along second are not. Your input column views x[{{},i}] from [ batches , sequence ]  tensor.  My tests show that it is better to feed x[i] from [sequence,batches] tensor. In my case on Titan X black  GPU speedup is from 6% to 12.5% % and only observable in CUDA mode on CPU there is no effect.

**Comment by karpathy** [comment]
Interesting, I didn't think this would be an issue since the x array is so "thin" and small compared to all the other compute that happens. I will look into this, thank you for reporting it.

**Comment by vseledkin** [comment]
It depends on model "geometry" small number of layers wide network-rnn_size large batch_size this increases amount of calculation non contiguous data involved into

**Comment by karpathy** [comment]
would a simple fix then be to call :contiguous() right after indexing into x? It should be very cheap at that point

**Comment by karpathy** [comment]
I pushed changes to master that incorporate this suggestion:
https://github.com/karpathy/char-rnn/commit/82baeead57e3dd3653b5b0f63fc6576fd6f14965

I am seeing about 15% speed improvement with default settings. Thank you for bringing this up!
