### ISSUE TITLE
Why do we need to carry over the rnn_state in the evaluation for batch prediction?

### ISSUE THREAD

**Issue by johnny5550822** [karpathy/char-rnn#118]
I am confused about the evaluation function in the code. Why do we need to carry the state of the previous batch to next batch? (in eval_split(split_index, max_batches)) Isn't it each batch are independent? Or I actually missing that, these batch are supposed to be in order?

      rnn_state[0] = rnn_state[#rnn_state]

**Comment by karpathy** [comment]
yes the batches must be in order, and we have to carry the state over from last split. They are definitely not independent batches.

**Comment by johnny5550822** [comment]
Thanks @karpathy. When we are creating batches, each batch are dependent to each other and that's why we need to carry the state over from last split. However, if my batch are independent, then I can re-initiate the state, am I right?

**Comment by karpathy** [comment]
yep!

**Comment by johnny5550822** [comment]
Great, thanks!

**Comment by wrapperband** [comment]
I am still learning as well, what type of process are you modelling where the batches aren't independent? and that change might help?
