### ISSUE TITLE
After the last commit

### ISSUE THREAD

**Issue by arushk1** [karpathy/char-rnn#121]
I have used char-rnn previously, but after the last commit, this is the error I get.

using CUDA on GPU 0...	
vocab.t7 and data.t7 do not exist. Running preprocessing...	
one-time setup: preprocessing input text file data/sher/input.txt/input.txt...	
loading text file...	
creating vocabulary mapping...	
/home/arush/torch/install/bin/luajit: ./util/CharSplitLMMinibatchLoader.lua:139: attempt to index global 'f' (a nil value)
stack traceback:
	./util/CharSplitLMMinibatchLoader.lua:139: in function 'text_to_tensor'
	./util/CharSplitLMMinibatchLoader.lua:38: in function 'create'
	train.lua:111: in main chunk
	[C]: in function 'dofile'
	...rush/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

**Comment by karpathy** [comment]
I doubt it's the last commit. It looks like your txt input file doesn't exist at that location

**Comment by arushk1** [comment]
Yes. I was giving it the path to the input file rather than the directory. Returning to it after a while. My bad
