### ISSUE TITLE
Question: How to reset all states after each sequence? [Duplicate]

### ISSUE THREAD

**Issue by kmnns** [karpathy/char-rnn#127]
(Marvelous kickstart code, thanks Andrej!)

I have modified the code to learn a word-based language model. (Specifically: to predict the last symbol in a sequence.)

The input data is a bunch of independent sentences. I want to make the task a bit easier for the network and reset all hidden states after each sequence (so it doesn't have to learn to reset them by itself).

I figured this function in `train.lua`, called after each sequence (at the end of `feval()` and `eval_split()`), should do the trick:

```lua
function reset_state()
    for t=1,opt.seq_length do
        clones.rnn[t].output[1]:zero()
        clones.rnn[t].output[2]:zero()
    end
end
```

It seems like a ridiculous low-level hack. A better way might be to comment out this line at https://github.com/karpathy/char-rnn/blob/master/train.lua#L289:

```lua
init_state_global = rnn_state[#rnn_state] -- NOTE: I don't think this needs to be a clone, right?
```

... and replace it with:

```lua
init_state_global = clone_list(init_state)
```

Is this a sensible thing to do, or have I misunderstood something here?

I have inspected `LSTM.lua` and `nn.gmodule`, but the odd variable names and dependencies still confuse me.

Related to: https://github.com/karpathy/char-rnn/issues/78

**Comment by hughperkins** [comment]
Seesm related to https://github.com/karpathy/char-rnn/issues/47 perhaps?

**Comment by kmnns** [comment]
Duplicate of https://github.com/karpathy/char-rnn/issues/47. Closed.
