### ISSUE TITLE
bad argument #1 to 'set'

### ISSUE THREAD

**Issue by hjyCoder** [karpathy/char-rnn#135]
/Users/huangjiyang/torch/install/bin/luajit: .../huangjiyang/torch/install/share/lua/5.1/nn/Identity.lua:13: bad argument #1 to 'set' (expecting number or torch.DoubleTensor or torch.DoubleStorage at /Users/huangjiyang/torch/pkg/torch/generic/Tensor.c:1123)
stack traceback:
	[C]: in function 'set'
	.../huangjiyang/torch/install/share/lua/5.1/nn/Identity.lua:13: in function 'func'
	...ngjiyang/torch/install/share/lua/5.1/nngraph/gmodule.lua:252: in function 'neteval'
	...ngjiyang/torch/install/share/lua/5.1/nngraph/gmodule.lua:287: in function 'forward'
	train.lua:270: in function 'opfunc'
	...uangjiyang/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
	train.lua:314: in main chunk
	[C]: in function 'dofile'
	...yang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0108c4c4c0

I get the error, when I follow the step.

**Comment by soumith** [comment]
hi @hjyCoder 

luarocks install nn

in your terminal, willl fix this issue. Sorry about that.

**Comment by jfsantos** [comment]
It seems there's something else here. `input` is a `torch.ByteTensor`, but the error states what `nn.Identity` really wants is a `torch.DoubleTensor`. Casting the input to double solves this issue.

**Comment by mrzl** [comment]
@jfsantos is this the fix you're talking about https://github.com/jfsantos/nn/commit/fb6056eff9ea1e84994c1811510748e82911161d ?

If not, can you please give directions, I'm in the same spot.

**Comment by jfsantos** [comment]
@mrzl: we actually found out the fix you referred to fixes this, but breaks other things. So your best bet now is to revert `Identity.lua` to how it was in torch/nn@89d238085.

**Comment by soumith** [comment]
Joao any chance you can send me a pr to revert to that? I'll quickly merge
it in

**Comment by jfsantos** [comment]
@soumith Just did it, it's at torch/nn#505.

**Comment by hjyCoder** [comment]
hi @soumith 
     Thank you for your comment, this issue is fixed.

Thanks.

**Comment by hughperkins** [comment]
I guess this issue can be closed?
