### ISSUE TITLE
learningRate not saved

### ISSUE THREAD

**Issue by Atcold** [karpathy/char-rnn#137]
`optim_state.learningRate` may be different from `opt.learning_rate`, since it could have been *decayed*.
Therefore, it should be saved in the *checkpoint* and restored upon retraining.
Perhaps, the whole `optim_state` should be saved in the *checkpoint* and restored upon retraining.

**Comment by karpathy** [comment]
the semantics of `init_from` is that you initialize the params, not that you resume training. The code doesn't resume training, and yes that would require saving `optim_state` as well.

**Comment by karpathy** [comment]
(so this is all working as intended, thought maybe could be documented better)

**Comment by Atcold** [comment]
OK, my bad, I misunderstood the purpose of that flag.
I've left some other comments in the code, if you have a bit of time.

**Comment by wrapperband** [comment]
Perhaps opt.learning_rate not being saved, that is one reason char-rnn  doesn't operate as I understood it either, ?
Any chance updateing the code to save opt.learning_rate? - if there was an option to use it or not when initialising an old checkpoint, , so the old (?) init operation can be used by anyone who would need that?

**Comment by Atcold** [comment]
P.S. @karpathy, we just met tonight, at NIPS 2015.
