### ISSUE TITLE
char-rnn is 7% slower on NVIDIA 940M since commit 82baee

### ISSUE THREAD

**Issue by hughperkins** [karpathy/char-rnn#145]
char-rnn is 7% slower on NVIDIA 940M, using defualt settings, since commit https://github.com/karpathy/char-rnn/commit/82baeead57e3dd3653b5b0f63fc6576fd6f14965

```
git checkout 4297a9bf
th train.lua
```
Iteration time 0.12s:
```
7/21150 (epoch 0.017), train_loss = 3.36680334, grad/param norm = 4.9234e-01, time/batch = 0.12s	
8/21150 (epoch 0.019), train_loss = 3.33023886, grad/param norm = 5.2171e-01, time/batch = 0.12s
```

```
git checkout 82baeea
th train.lua
```
Iteration time 0.13s:
```
20/21150 (epoch 0.047), train_loss = 3.27903176, grad/param norm = 4.0448e-01, time/batch = 0.1315s	
21/21150 (epoch 0.050), train_loss = 3.32281955, grad/param norm = 4.2330e-01, time/batch = 0.1343s	
```

**Comment by karpathy** [comment]
poof. Well, ... the way it is right now makes the code much nicer and cleaner, and works faster on my high-end GPUs, so I think we'll keep the current version. Not sure why the 940M prefers a weird strided access pattern (e.g. `arr[{ {}, {1,2} }]`). Normally doing stuff like this is slower.

**Comment by hughperkins** [comment]
Alright, fair enough :-)  yes, I should try it on something a bit faster than a mobile GPU really :-D  Just out of curiosity, what GPU are you using, what settings, and what iteration time does that give?

**Comment by karpathy** [comment]
I think I was running my timing experiments on a K40 or a Titan Z. I'd use a Titan X now.
