### ISSUE TITLE
on clone_many_times()

### ISSUE THREAD

**Issue by jasonylee** [karpathy/char-rnn#155]
Hi Andrej,

I noticed your model_utils.clone_many_times() function makes a deep copy of the network , giving you seq_length copies of the network with no parameter sharing. Don't we want to share the parameters of the RNN (e.g. i2h, h2h, etc)?

During forward pass you're passing intermediate hidden states from one RNN to the next, but the neighbouring RNNs have different parameter values, so essentially this is a feedforward network of depth seq_length with a connection from the last layer back to the first. Am I missing something? Would appreciate a clarification.

I realised your clone_many_times() function was taken from zaremba's g_cloneManyTimes(), and submitted an issue there, but thought I might as well ask here too in case someone can shed some light on this.

Cheers

**Comment by MTSranger** [comment]
After doing a deep clone, it then takes all the parameter Tensors of the clone and point them back to the original network, so that the parameters are shared. Specifically, this is done on line 143 and 144 on char-rnn/util/model_utils.lua

```
            for i = 1, #params do
                cloneParams[i]:set(params[i])
                cloneGradParams[i]:set(gradParams[i])
            end
```

**Comment by jasonylee** [comment]
Thanks a lot, makes sense now. Closing issue.
