### ISSUE TITLE
Justification of cloning `rnn` and `criterion`

### ISSUE THREAD

**Issue by jasonylee** [karpathy/char-rnn#159]
Hi @karpathy ,

I've been wondering why we clone `rnn` and `criterion` `seq_length` times. Just wanted to clarify my understanding with people.

It seems that cloning `criterion` is unnecessary, as we can do with just one. I confirmed this by replacing `clones.criterion[t]` with `clones.criterion[1]` in the code and there was no difference in the results.

Initially I also couldn't see though why we clone `rnn`, especially given that they share the same parameters ( #155 ). On further investigation I realised that if we only had a single `rnn`, we'll have to apply `forward()` `seq_length` times and then `backward()` `seq_length` times, but this is not how torch works. You have to apply `forward()` and then immediately `backward()` for a module to learn properly. Am I on the right lines? Would appreciate any comment cheers!

**Comment by MTSranger** [comment]
Your understanding is essentially correct, I think. Basically, `backward()` in a complicated module usually has several dependencies that require a call to `forward()` first. For example, you need to input and output for all the intermediate layers to be able to back-prop correctly.

Some modules also keep track of other information like the input size (e.g. for convolution layers), or which node was dropped out. Dropout is non-deterministic so you can't even apply the trick of calling `forward()` again right before the `backward()` call; cloning is a relatively clean solution that works in all cases.

**Comment by jasonylee** [comment]
thanks! closing.
