### ISSUE TITLE
Luarocks nn install fail

### ISSUE THREAD

**Issue by LinuxFTW** [karpathy/char-rnn#195]
So, I was trying to install nn because it was required code. Then, it ended with a build error. Error Code below
Error Code:
`/home/jman/torch/install/include/TH/generic/THTensorMath.h:77:13:` note: in expansion of macro ‘THTensor_’
 TH_API void THTensor_(sum)(THTensor *r_, THTensor *t, int dimension);
             ^
lib/THNN/CMakeFiles/THNN.dir/build.make:62: recipe for target 'lib/THNN/CMakeFiles/THNN.dir/init.c.o' failed
make[2]: *** [lib/THNN/CMakeFiles/THNN.dir/init.c.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'lib/THNN/CMakeFiles/THNN.dir/all' failed
make[1]: *** [lib/THNN/CMakeFiles/THNN.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
`

**Comment by woolgathering** [comment]
You're probably working with an old version of Torch. Running `luarocks install torch` worked for me.
