### ISSUE TITLE
github gist link is broken

### ISSUE THREAD

**Issue by scotthuang1989** [karpathy/char-rnn#211]
Hi Karpathy,

The gist link you provide: https://gist.github.com/karpathy/d4dee566867f8291f086 is broken, could you kindly provide a new one? I really want try it.

**Comment by cuuupid** [comment]
![image](https://user-images.githubusercontent.com/6960204/36814743-6897bcc6-1cd0-11e8-978b-512862376458.png)

Link works for me ([same link](https://gist.github.com/karpathy/d4dee566867f8291f086))

**Comment by scotthuang1989** [comment]
thanks. I can open it with a vpn now. I never need a vpn for github before, so I don't even tried it. sorry for the trouble.
