### ISSUE TITLE
nngraph not installable via default luarocks?

### ISSUE THREAD

**Issue by hughperkins** [karpathy/char-rnn#22]
- awesome tutorials :-)  I mean, AWESOME! :-)
- I tried many variations of typing `luarocks install nngraph`, but all failed :-P  Fairly sure it is not in the default repository? https://luarocks.org/search?q=nngraph  I guess the installation method for now is to git clone git@github.com:torch/nngraph.git ,and then install the rockspec from that clone?

**Comment by JacobEdelman** [comment]
You have to install Torch first. I had the same problem.
