### ISSUE TITLE
Th: command not found, Torch installed fine 

### ISSUE THREAD

**Issue by BadCoder2** [karpathy/char-rnn#221]
After installing torch twice, I still get th: command not found error.

**Comment by AlekzNet** [comment]
Did you add the PATH to torch/install/bin?

**Comment by BadCoder2** [comment]
If you mean type source./profile, yes, however, it just returns "No such file or directory."
Otherwise, no.

**Comment by BadCoder2** [comment]
Sorry, I just looked up your suggestion. Thanks! Closing issue.
