### ISSUE TITLE
Question: Is there a way to "pause" temporarily without making it restart?

### ISSUE THREAD

**Issue by BadCoder2** [karpathy/char-rnn#222]
I can't really leave my computer active overnight for many reasons, most outstanding being the risk of overheating. I was wondering if there was a way to pause the NN while I did other things? Thanks.

**Comment by AlekzNet** [comment]
What about `Ctrl-S ` ?

**Comment by AlekzNet** [comment]
Then `Ctrl-Q` to proceed.

**Comment by BadCoder2** [comment]
This wasn't exactly what I was looking for, but it works nonetheless. Thanks for the reply, closing issue.
