### ISSUE TITLE
Unable to run the tinyshakespeare example

### ISSUE THREAD

**Issue by youngestachiever** [karpathy/char-rnn#26]
Hello,

Thank you very much for the awesome knowledge share. I'm pretty new to lua and torch. When I'm trying to run this example on my CPU, I get the following error. From what I could infer, I understand that the variable 'path' is not being set. A fair amount of googling didn't help. Also tried an unholy, setting a local variable path to the present working directory, the next problem was in checking if path.exists. So, I'm pretty confused. 

Here is the trace I get, when I do a th train.lua with a datadir and gpuid flag.

/home/cyber-chivalry/torch/install/bin/luajit: ./util/CharSplitLMMinibatchLoader.lua:15: attempt to index global 'path' (a nil value)
stack traceback:
	./util/CharSplitLMMinibatchLoader.lua:14: in function 'create'
	train.lua:75: in main chunk
	[C]: in function 'dofile'
	...1459/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

Can you please check this. Thank you in advance.

**Comment by bshillingford** [comment]
Maybe try adding `local path = require 'pl.path'` to the top of all files that have that error, you might be missing this: https://stevedonovan.github.io/Penlight/api/libraries/pl.path.html

**Comment by youngestachiever** [comment]
Thank you very much bshillingford.

`luarocks install penlight` just did the trick. Not sure how it got missed while installing. 

Closing this ticket. Thank you again.

**Comment by SevenBlocks** [comment]
I had the same issue. Adding <code>local path = require 'pl.path'</code> and installing penlight worked.

**Comment by zhuth** [comment]
`luarocks install penlight` really works. Thanks!
