### ISSUE TITLE
Resume training from a checkpoint 

### ISSUE THREAD

**Issue by namp** [karpathy/char-rnn#33]
For some reason char-rnn training was interrupted. Is it possible to resume training from e.g. the latest checkpoint file?

**Comment by karpathy** [comment]
Currently this is not possible, sorry. It should be, I'll add it to my todo list (currently at a conference, will be able to put some dev time into this in ~few days or so perhaps)

**Comment by namp** [comment]
Perfect, thanks!

**Comment by eternaldensity** [comment]
Yes, this will be a helpful feature, thanks!

**Comment by karpathy** [comment]
Update: This has just been implemented, use the `init_from` option during training.

**Comment by namp** [comment]
Fantastic! Many thanks

**Comment by eternaldensity** [comment]
Excellent, it works!  (Also I've fixed my Ubuntu after a failed cuda 7
installation broke my graphics driver somehow.  That was 'fun'.  And
irrelevant, sorry.)

**Comment by canpoyrazoglu** [comment]
How does it exactly work? I've done some training for hours, it has saved many files into the cv folder. Then, I've resumed with the latest file in cv folder like:

`172-15-43-191:char-rnn-master Can$ th train.lua -init_from cv/lm_lstm_epoch16.12_1.2903.t7 `

Here is the output:

    using CUDA on GPU 0...  
    loading data files...   
    cutting off end of data so that the batches/sequences divide evenly 
    reshaping tensor... 
    data load done. Number of data batches in train: 1737, val: 92, test: 0 
    vocab size: 67  
    loading a model from checkpoint cv/lm_lstm_epoch16.12_1.2903.t7 
    overwriting rnn_size=128, num_layers=2, model=lstm based on the checkpoint. 
    setting forget gate biases to 1 in LSTM layer 1 
    setting forget gate biases to 1 in LSTM layer 2 
    number of parameters in the model: 241603   
    cloning rnn 
    cloning criterion   
    1/86850 (epoch 0.001), train_loss = 1.54819668, grad/param norm = 4.4958e-02, time/batch = 0.3569s  
    2/86850 (epoch 0.001), train_loss = 1.26299617, grad/param norm = 4.3240e-02, time/batch = 0.2289s  
    3/86850 (epoch 0.002), train_loss = 1.27801491, grad/param norm = 5.3360e-02, time/batch = 0.1961s  
    ...

It does see and read the file, but it starts from beginning. I'm trying to train with the default Shakespeare pieces. Why?

**Comment by eternaldensity** [comment]
When you resume from a checkpoint, it counts from zero.  It's not actually
starting from a point of no training though.

**Comment by fengs** [comment]
Lesson, don't include `-data_dir data/***` in the command if `-init_from`. It will overwrite the vocabulary and cause inconsistency which cannot be recovered.
```
ubuntu@ip:~/char-rnn$ th train.lua -init_from cv/lm_lstm_epoch25.98_1.0748.t7
...
/home/ubuntu/torch/install/bin/luajit: train.lua:137: error, the character vocabulary for this dataset and the one in the saved checkpoint are not the same. This is trouble.
```
