### ISSUE TITLE
package cutorch, cunn not found

### ISSUE THREAD

**Issue by bomattin** [karpathy/char-rnn#37]
* OS: Kali Linux

I've already installed torch,

With `luarocks install cutorch` I get a successful build, same with `luarocks install cunn`.

Yet, when I run with a GPU, I get 

    package cunn not found!
    package cutorch not found!

And the program reverts to CPU mode.

**Comment by karpathy** [comment]
sorry about this, I was just hacking on this part and may have broken the build somehow. I'll fix this asap, I don't have access to a GPU machine to figure out what's going on at this moment. Hopefully within few hours.

**Comment by bomattin** [comment]
No worries, I can take a peek at it myself. Do you have a file name I can look at or a commit hash I could possibly revert?

**Comment by karpathy** [comment]
I was trying to be clever with a few of the most recent commits. The issue is where you see them imported, `local ok,cunn = pcall...`, maybe they don't work as I thought they did. I'll look into this in a bit

**Comment by karpathy** [comment]
I think I got it. There shouldn't be `local` for the `pcall` lines. Taking it out works I think.

**Comment by bomattin** [comment]
I just took them out, doesn't appear to be working. I'll tinker around with it a bit to see if it's specific to my implementation.

**Comment by karpathy** [comment]
hey, I finally had a chance to check this and current code works without issues on my GPU machine. It could be something with your configuration.

**Comment by bomattin** [comment]
Roger that. I'll mark it closed and start checking paths and global/env variables. Thanks for getting to this so quickly!

**Comment by bomattin** [comment]
Got it...was in fact implementation specific. Forcing the `require` without `pcall` gave me a stacktrace with a CUDA runtime error.

**Comment by karpathy** [comment]
Interesting. Is the stacktrace helpful? Let me know if you resolve this.

**Comment by bomattin** [comment]
Yeah, it was an error about insufficient versions. I forced installing Cuda 5.5 as I saw it in one of the libraries (Torch, maybe?) but I'm going to see if Cuda 7 will work, unless you've got a better suggestion.

**Comment by soumith** [comment]
Can you post that stacktrace here? Cuda 5.5 to 7.0 should work comfortably.

Your gpu needs to be atleast CUDA 2.0 capable.

**Comment by bomattin** [comment]
Yeah, it'll be an hour or so, right now I'm getting an Ubuntu distro on another partition to see if I can get this running sooner.

**Comment by eternaldensity** [comment]
For me, removing the pcall for the require changes the error to 'no CUDA-capable device', so what I thought was a package error for the past several hours actually wasn't.

So now I'm back to figuring out what's up with my CUDA installation...

**Comment by bomattin** [comment]
@eternaldensity What OS and GPU are you using?

I was able to get this working on Ubuntu 12.04 LTS without issue. A lack of full headers (version.h) in Kali makes CUDA installation difficult. I've submitted a PR which generates a little more feedback, since `pcall ` will return false on ANY `require` failure, not just missing packages.

**Comment by eternaldensity** [comment]
@bomattin 
Ubuntu 17.04 LTS
I've tried Cuda 7, and then 6.5 when I found that was recommended for my GPU (GTS 250M).  I installed via the runfile method, first by installing everything, and a second attempt extracting the driver installer so I could run it with --no-opengl-files which didn't help.

Actually the attempt with Cuda 7 was the most successful because that time I could still get to the Ubuntu login screen (it had the wrong resolution, and attempts to login resulted in a screen flicker and threw me back to the login screen) while with Cuda 6.5 it never succeeded in reaching full graphics mode at all.

Since the Cuda 7 attempt I've upgraded my Nvidia drivers from 331 to 340 (recommended for my GPU on the Nvidia site) so maybe another attempt will be more successful.  Tomorrow.

**Comment by e9t** [comment]
Hi, I'm using Ubuntu 14.04 with CUDA 7.0.27 and solved the same problem by upgrading `cmake`.
Additional details below.

First, I successfully installed the following with no errors:
``` bash
$ luarocks install cutorch
$ luarocks install cunn
```

However, Torch complained about not being able to find them, and fell back to CPU:
```
package cunn not found!
package cutorch not found!
```

So I opened a Torch REPL and just tried loading `require 'cutorch'`:
```
th> require 'cutorch'
/home/epark/torch/install/share/lua/5.1/trepl/init.lua:363: cuda runtime error (30) : unknown error at /tmp/user/1000/luarocks_cutorch-scm-1-1963/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
        [C]: in function 'error'
        /home/epark/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        [string "_RESULT={require 'cutorch'}"]:1: in main chunk
        [C]: in function 'xpcall'
        /home/epark/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
        ...park/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406670
```

Googled the traceback and found an issue at the cutorch repo saying that I'd have to upgrade my cmake (https://github.com/torch/cutorch/issues/126):
```
$ cmake --version
cmake version 2.8.12.2
```

I had to [use a PPA](http://askubuntu.com/a/610352/138835) to upgrade my cmake to version 3.2:
```
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:george-edison55/cmake-3.x
$ sudo apt-get update
$ sudo apt-get install cmake
$ cmake --version
cmake version 3.2.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Then I reinstalled cutorch and cunn according to https://github.com/torch/cutorch/issues/210 (In case this doesn't work on the first try, check if you have the permissions for `~/.cache/luarocks`):

```
$ luarocks install cutorch
$ luarocks install cunn
```
Hope that helps anyone else who encounters the same problem.
