### ISSUE TITLE
syntax error when trying to train

### ISSUE THREAD

**Issue by triola** [karpathy/char-rnn#43]
I believe I have things setup correctly on my Mac environment.

I run "th train.lua -data_dir data/tinyshakespeare -gpuid -1 -eval_val_every 3600"
and I get "syntax error: [string "th train.lua -data_dir data/tinyshakespeare -..."]:1: '=' expected near 'train'"

**Comment by triola** [comment]
ah, my error was in thinking that I should first run "th" to open torch, and then run the train commands.

If anyone else has this issue, run "th train.lua -data_dir data/tinyshakespeare -gpuid -1 -eval_val_every 3600" directly from bash

**Comment by ChidanandKumarKS** [comment]
@triola 
Iam also facing the same issue. Kindly let me know how u have solved
