### ISSUE TITLE
gpuids should probably start from 1 :-)

### ISSUE THREAD

**Issue by hughperkins** [karpathy/char-rnn#56]
Hi Andrej,

I think that it would be more consistent with how lua/torch works if gpuids start from 1.  I know this would be backwards-incompatible breaking api change though, hence not submitting a PR for this.  It is a bit confusing though, eg, if you use `cutorch.getDeviceProperties(1)` or `cltorch.getDeviceproperties(1)`, and ditto for 2,3 etc, to figure out which device you would use, it might be considered confusing to have to then subtract one from this deviceid in order to run train.lua :-)

```
th> cutorch.getDeviceProperties(1)
{
  computeMode : 0
  memPitch : 2147483647
  canMapHostMemory : 1
  warpSize : 32
  pciDeviceID : 0
  pciBusID : 4
  totalConstMem : 65536
  pciDomainID : 0
  integrated : 0
  deviceOverlap : 1
  maxThreadsPerBlock : 1024
  clockRate : 980000
  maxTexture1D : 65536
  minor : 0
  name : "GeForce 940M"
  freeGlobalMem : 1007845376
  maxTexture1DLinear : 134217728
  kernelExecTimeoutEnabled : 0
  sharedMemPerBlock : 49152
  major : 5
  totalGlobalMem : 1073610752
  regsPerBlock : 65536
  textureAlignment : 512
  multiProcessorCount : 3
}
                                                                      [0.0011s]
th> cutorch.getDeviceProperties(0)
[string "_RESULT={cutorch.getDeviceProperties(0)}"]:1: cuda runtime error (10) : invalid device ordinal at /home/user/git/cutorch/init.c:626
```

```
th> cltorch.getDeviceProperties(1)
{
  deviceType : "GPU"
  localMemSizeKB : 47
  globalMemSizeMB : 1023
  deviceVersion : "OpenCL 1.1 CUDA"
  platformVendor : "NVIDIA Corporation"
  deviceName : "GeForce 940M"
  maxComputeUnits : 3
  globalMemCachelineSizeKB : 0
  openClCVersion : "OpenCL C 1.1 "
  maxClockFrequency : 980
  maxMemAllocSizeMB : 255
  maxWorkGroupSize : 1024
}
                                                                      [0.0009s]
th> cltorch.getDeviceProperties(0)
[string "_RESULT={cltorch.getDeviceProperties(0)}"]:1: Device doesnt exist at /home/user/git/cltorch/init.cpp:69
```
(Edit: hmmm, cutorch.getDeviceProperties() returns tons more info than cltorch.getDeviceProperties() :-P )

**Comment by karpathy** [comment]
Hi, I do this because when you do `nvidia-smi` or any other similar diagnostic tool in the console that prints information about the GPUs it always starts with 0. I understand it's confusing if you're using Torch things and inside lua, but given that it is backwards incompatible I don't think it's worth changing at this point.

**Comment by hughperkins** [comment]
Fair enough :-)
