### ISSUE TITLE
Mutil-GPU support?

### ISSUE THREAD

**Issue by ZachzZ** [karpathy/char-rnn#57]
Is there a existed way to support multi-GPU for training because memory of one GPU is not enough for a large amount of data. 
It seems only a little change is needed based on Torch7. So if there is no existed way, I will do it myself.

**Comment by ZachzZ** [comment]
It seems cutorch doesn't support multi-gpu in a natural way. But we can do it manually following this issue https://github.com/torch/cutorch/issues/42#issue-43657470. The main problem is to synchronize the model parameter in every bp.

**Comment by sherjilozair** [comment]
@ZachzZ Did you ever try doing this? Any progress?

**Comment by ZachzZ** [comment]
@sherjilozair I have some new GPUs with more memory then. So I do not need to look into this problem yet. What's more, I think we can use multi-gpu like distributed parameter server, which will make it much easier.
