### ISSUE TITLE
sequence to sequence

### ISSUE THREAD

**Issue by imaglib** [karpathy/char-rnn#65]
hi karpathy,
    I want to build a sequence to sequence model, something like QA model, is it possible to use this tools to do experiments?

**Comment by karpathy** [comment]
yes. You'd have to change the code quite substantially of course, but this gives you an idea of what's involved at least, and how to put things together.

**Comment by ananda621** [comment]
@imaglib, I'm involved in this same task. Still developing, may be we could collaborate? Reach me at anandan@umich.edu

**Comment by ffmpbgrnn** [comment]
Hi guys, I am implementing encoder-decoder with GRU using Torch as well. It seems in the [original paper](http://arxiv.org/pdf/1406.1078.pdf) the decoder is conditioned on the encoder output. Does anyone have experience on this? Will it affect the performance a lot if I just eliminate the encoder context?

**Comment by karpathy** [comment]
There are no plans currently to allow char-rnn to perform sequence-to-sequence prediction. Closing the issue.
