### ISSUE TITLE
 Error loading module 'libnn' while trying to run

### ISSUE THREAD

**Issue by rracinskij** [karpathy/char-rnn#69]
Hi, 

I am trying to run this awesome code, but run into following error:
/usr/local/bin/luajit: /usr/local/share/lua/5.1/luarocks/loader.lua:113: error loading module 'libnn' from file '/usr/local/lib/lua/5.1/libnn.so':
	dlopen(/usr/local/lib/lua/5.1/libnn.so, 6): Symbol not found: _THArgCheck
Would greatly appreciate any help.

**Comment by ryaneleary** [comment]
Have you installed all of the requirements listed in the [readme](https://github.com/karpathy/char-rnn/blob/master/Readme.md)?

**Comment by rracinskij** [comment]
I have trouble with installing cutorch+cunn/cltorch+clnn packages, but using -gpuid flag to force using CPU doesn't help either.

**Comment by hughperkins** [comment]
Can you make sure you update all of the following packages and try again:
```
luarocks install torch7
luarocks install nn
luarocks install nngraph
```
If that fails, can you reinstlal nn:
```
luarocks remove --force nn
luarocks install nn
```

**Comment by rracinskij** [comment]
Now the error changed to "dyld: lazy symbol binding failed: Symbol not found: _lua_setglobal
  Referenced from: /usr/local/lib/lua/5.1/libtorch.so". It looks like a more general issue, I'll try to reinstall everything once again or run the code on another machine. Thank you for your help.

**Comment by hughperkins** [comment]
Yes, I think that sounds like a good plan :-)

**Comment by fmassa** [comment]
@rracinskij you are maybe using an old install from torch, which is global.
Try uninstalling your global installation using 
```
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash
```
from https://github.com/torch/ezinstall, and then install it again following the instructions from http://torch.ch/docs/getting-started.html#_

**Comment by rracinskij** [comment]
Thank you, @fmassa!
Finally solved the problem by uninstalling using 
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash 
and reinstalling from https://github.com/torch/ezinstall.
Many thanks to everyone!
