### ISSUE TITLE
Train Error on GPU ClassNLLCriterion.lua:34: bad argument #1 (field weights does not exist)

### ISSUE THREAD

**Issue by shuokay** [karpathy/char-rnn#76]
Hi Karpathy,

I am practicing rnn with your char-rnn project. I followed the project readme step by step. When I train the rnn on CPU with command:
```
th train.lua -data_dir data/tinyshakespeare/ -gpuid -1
```
everything goes well. But When I checkout to GPU by 
```
th train.lua -data_dir data/tinyshakespeare/
```
the torch complained:
```
/home/gys/torch/install/bin/luajit: ...gys/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:34: bad argument #1 (field weights does not exist)
stack traceback:
        [C]: in function 'ClassNLLCriterion_updateOutput'
        ...gys/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:34: in function 'forward'
        train.lua:254: in function 'opfunc'
        /home/gys/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
        train.lua:293: in main chunk
        [C]: in function 'dofile'
        .../gys/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406670
```
I have a Tesla K40 GPU and using CUDA 7.0 and CUDA 7.5. I have try to make soft link to CUDA 7.0 and 7.5 and change the LD_LIBRARY_PATH accordingly.
Before this, I am wroking with Caffe to train CNN models.

I am very new to torch7, I have work on this issue for some time, but still can figure out the reason. can you sincerely help me to find the solution?

**Comment by raidancampbell** [comment]
I also experienced this error.  Unfortunately, I have been poking around quite a bit in an effort to solve an unrelated issue.

If I recall correctly, I tried `luarocks install nn`, which may have fixed it, then `luarocks install torch`, which fixed not being able to find the `cunn` and `cutorch` libraries

**Comment by shuokay** [comment]
Everything goes well now. first I update the torch by ```update.sh```, then I link the cuda to cuda-7.5, then I run the torch's ```./install.sh``` again. then everything goes well. But I still can't figure the problem. I just resolve this problem by accident. Hope this can help somebody.
I will close this issue.

**Comment by danbri** [comment]
fwiw I've seen this recently too

**Comment by danbri** [comment]
see also https://github.com/torch/nn/commit/6bcdc6f74873a214d90ac1418da86dc0f75048fc ... I fixed an installation by brutishly copying in latest version of that class over the top of luajit. #notproud

**Comment by karpathy** [comment]
I'm not sure what's the cause for this issue or when it started. Is it cuda version dependent?

**Comment by raidancampbell** [comment]
I can confirm that I did update CUDA before this happened, but I can't confirm that the update was the cause, as I twiddled with too many other things in that time

**Comment by soumith** [comment]
the nn and cunn versions looks out of date. that's what this error message is about.

**Comment by alterya** [comment]
Just writing down my fix for the same error:

```bash
user@xyz:~/code/char-rnn$ th train.lua -data_dir data/tinyshakespeare
using CUDA on GPU 0...
vocab.t7 and data.t7 do not exist. Running preprocessing...
one-time setup: preprocessing input text file data/tinyshakespeare/input.txt...
loading text file...
creating vocabulary mapping...
putting data into tensor...
saving data/tinyshakespeare/vocab.t7
saving data/tinyshakespeare/data.t7
loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
data load done. Number of data batches in train: 423, val: 23, test: 0
vocab size: 65
creating an lstm with 2 layers
number of parameters in the model: 240321
cloning rnn
cloning criterion
/Users/user/code/torch/install/bin/luajit: ...ode/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:50: bad argument #1 to 'ClassNLLCriterion_updateOutput' (torch.CudaTensor expected, got nn.ClassNLLCriterion)
stack traceback:
	[C]: in function 'ClassNLLCriterion_updateOutput'
	...ode/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:50: in function 'forward'
	train.lua:254: in function 'opfunc'
	.../user/code/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
	train.lua:293: in main chunk
	[C]: in function 'dofile'
	...code/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x010e40f2e0
```

I am using Cuda 7.0 on NVIDIA GeForce GT 650M on my Macbook Pro

Updating torch alone did not help.

As suggested by @raidancampbell I've run `luarocks install nn` and it resolved the problem.

**Comment by ajkl** [comment]
+1 `luarocks install nn` worked for me too. PR - https://github.com/karpathy/char-rnn/pull/92

**Comment by dxyzab** [comment]
the changes the current nn need to be merged into getParamsByDevice otherwise data parallel wont work
