### ISSUE TITLE
cutorch problem - invalid argument at (...)/cutorch/lib/THC/THCTensor.cu:32

### ISSUE THREAD

**Issue by ttajmaje** [karpathy/char-rnn#81]
I run into an error when trying to execute char-rnn with CUDA support:

$ th train.la -data_dir data/tinyshakespeare/ -gpuid 0
using CUDA on GPU 0...	
loading data files...	
cutting off end of data so that the batches/sequences divide evenly	
reshaping tensor...	
data load done. Number of data batches in train: 423, val: 23, test: 0	
vocab size: 65	
creating an lstm with 2 layers	
/home/ttajmaje/priv/rnn/torch/distro/install/bin/lua: train.lua:156: cuda runtime error (11) : invalid argument at /tmp/luarocks_cutorch-scm-1-5019/cutorch/lib/THC/THCTensor.cu:32
stack traceback:
	[C]: in function 'clone'
	train.lua:156: in main chunk
	[C]: in function 'dofile'
	...rch/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: in ?

Using CUDA 5.5 SDK
Lua 5.2

th> getDeviceProperties(1)
{
  computeMode : 0
  minor : 1
  memPitch : 2147483647
  sharedMemPerBlock : 49152
  warpSize : 32
  pciBusID : 1
  totalConstMem : 65536
  multiProcessorCount : 2
  major : 2
  clockRate : 1500000
  totalGlobalMem : 1072889856
  name : "GeForce GT 630"
  integrated : 0
  regsPerBlock : 32768
  kernelExecTimeoutEnabled : 1
  textureAlignment : 512
  maxTexture1D : 65536
  pciDeviceID : 0
  pciDomainID : 0
  maxTexture1DLinear : 134217728
  freeGlobalMem : 661180416
  canMapHostMemory : 1
  deviceOverlap : 1
  maxThreadsPerBlock : 1024
}

Any idea what may be the cause ?

**Comment by soumith** [comment]
when you get a cudaRuntimeError, the first thing I recommend is to upgrade from CUDA 5.5 to CUDA 7.0 (or 7.5).

**Comment by ttajmaje** [comment]
That would be tricky as CUDA 7.0 does not support 32bit systems anymore and I don't have an easy option to switch to 64bit distro. 
Thanks anyway.

**Comment by karpathy** [comment]
Closing this issue, as it seems an old CUDA version was used here. The 32 vs. 64 bit and CUDA 7.0 incompatibility seems like a sad issue, but char-rnn independent one.
