### ISSUE TITLE
Peephole connections

### ISSUE THREAD

**Issue by alexkruegger** [karpathy/char-rnn#84]
At first, thank you for this amazing library and the corresponding article! It is really very nice!
Sorry for question, but if I understand correctly, the current implementation of the LSTM doesn't include peepholes connection from cell to ig, og, fg. (http://www.felixgers.de/papers/phd.pdf). Can you pls explain the reason?

**Comment by karpathy** [comment]
because they are useless

**Comment by alexkruegger** [comment]
It seems (possible I'm wrong) that for some class of tasks, peephole connections can increase model performance. But to check it we need the ability to test it. The char_rnn is really very cool library for playing around wide class of tasks, and as I think adding the ability to use peepholes make it better )
Can I kindly ask you to think about adding this feature to the code?

P.S. Perhaps I really mistake about peepholes usefulness, so just ignore my opinion and I close the issue.
