### ISSUE TITLE
How do I know GPU is running instead of CPU?

### ISSUE THREAD

**Issue by johnny5550822** [karpathy/char-rnn#89]
Hi,

When I was training the model, I checked "nvidia-smi" and found that my GPU (Tesla K40) seems not occupied. But I did not use the "-gpuid" option, which meant by default the GPU should be used. 

Is there any way to check if my GPU is using? (I don't have any compilation error while I am compiling torch7).

Thanks!

**Comment by johnny5550822** [comment]
I guess I found the answer. Basically, the train.lua check if the cunn and cutorch is installed properly at the beginning. If so, gpu is used. If not, cpu is used.

**Comment by johnny5550822** [comment]
However, I have used the local luarocks in torch7 folder and do "luarocks list" and see I installed cunn and cutorch, but I don't know why the program gives me an error that I don't have them. I have tried to rebuild cunn and cutorch (locally inside the torch folder), and this does not help.

**Comment by hughperkins** [comment]
try running hte commands yourself, and see what happens, like `th -l cutorch` and `th -l cunn`

**Comment by johnny5550822** [comment]
oh...it said could not load cunn....what that mean?

**Comment by johnny5550822** [comment]
but when I do luarocks, I saw:

cunn
   scm-1 (installed) - /home/johnny5550822/torch/install/lib/luarocks/rocks

cunnx
   scm-1 (installed) - /home/johnny5550822/torch/install/lib/luarocks/rocks

cutorch
   scm-1 (installed) - /home/johnny5550822/torch/install/lib/luarocks/rocks

**Comment by soumith** [comment]
run:
luajit -lcutorch
luajit -lcunn

report what the errors are.

**Comment by johnny5550822** [comment]
luajit: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /home/johnny5550822/torch/extra/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: at 0x7f85b1d60e10
	[C]: in function 'require'
	...hnny5550822/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: in function 'require'
	.../johnny5550822/torch/install/share/lua/5.1/cunn/init.lua:1: in main chunk
	[C]: at 0x0047d760
	[C]: at 0x00405970

**Comment by soumith** [comment]
you have your answer right there.

**Comment by johnny5550822** [comment]
I am using Cuda 7, is that not enough?

**Comment by hughperkins** [comment]
Seems like the driver itself is older?  nvidia-smi should tell you which versoin of the driver you are using (for example, on my computer ,it says '346.59')

**Comment by johnny5550822** [comment]
@hughperkins Ya, I am using 340.76. I guess I need the 346.89 for CUDA 7.0 and Tesla K40. Thanks!

**Comment by johnny5550822** [comment]
after I upgrade my driver to match the kernel, I got following error when I run luajit -lcutorch

luajit: ...hnny5550822/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/johnny5550822/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'require'
	...hnny5550822/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: at 0x0047d760
	[C]: at 0x00405970

**Comment by fmassa** [comment]
@johnny5550822 did you tried recompiling cutorch and cunn after you updated your cuda ?

**Comment by johnny5550822** [comment]
@fmassa so what happen is when I try to match the version of nvidia driver and cuda, I have to forced to use nvidia driver 340 because I have Tesla K40 but Quadro FX580 (which is not supported by driver 346). As a result, my cuda is downgraded to 5.5. 

I try to recompile the cunn and cutorch, but I fail. :(

**Comment by soumith** [comment]
Johnny your card is not supported by torch. Very sorry about that. Hope you
will get to try torch soon with newer card.

**Comment by johnny5550822** [comment]
ah :( you mean my card, you mean tesla K40 or Quadro FX580?

**Comment by soumith** [comment]
Fx 580.

**Comment by johnny5550822** [comment]
But if I only use teslaK40 to do GPU computing, isn't it that fine?

**Comment by soumith** [comment]
Nvidia driver installs might not work that way. I am not sure.

**Comment by johnny5550822** [comment]
Ya, I agree. After a long fixing (from this afternoon till now, which is midnight), I think cuda 6.5 or above need nvidia driver 346, but this driver does not support FX580 :(....

However, before, cuda6.5 is okay with driver 340. I don't know they upgrade it and then everything break now....

**Comment by hughperkins** [comment]
Tesla K40 is a nice card :-)

**Comment by hughperkins** [comment]
I googled a few weeks ago, when someone had a similar issue, and seems like there is a permisisons issue with the v5 or so driver.  You could try googling, and you might find hte article I saw about that.

**Comment by johnny5550822** [comment]
@hughperkins Thanks! I will try to see if this problem can be taken care so less people will suffer!

**Comment by hughperkins** [comment]
Oh, seems like that would be short-lived solution anyway, since cutorch is going to be firmly on v7 sooner rather than later https://github.com/torch/cutorch/issues/148

**Comment by johnny5550822** [comment]
@hughperkins I guess I need to upgrade my FX580...

**Comment by hughperkins** [comment]
This was the relevant thread, https://github.com/torch/cunn/pull/107 , linked newsgroup thread https://groups.google.com/forum/#!topic/torch7/WAaDEAB9KV8 and I googled something like ... sorry, cant remember what I googled :-(

**Comment by hughperkins** [comment]
(Oh, I probably googled something like 'cuda 5 cudaGetDeviceCount', or something, since the line that failed in that thread was:

```
cudaGetDeviceCount(&count);
```

**Comment by hughperkins** [comment]
Yeah, upgrading the FX580 sounds like a good plan :-)

**Comment by johnny5550822** [comment]
@hughperkins no problem! Thank you very much. Actually, what happen I manage to recompile different part of torch with different version of gcc (4.9 and 4.4). And after recompiling the code, I am able to use the GPU! Although I think the it is temporarily working, it is still encouraging :). I will update my driver card later. Thanks!

**Comment by re-identification** [comment]
hi, I have install cunn and cutorch but when I run my code; my system don't utilize GPU. its start running on cpu. what should I do

**Comment by re-identification** [comment]
@johnny5550822  how you finally solve this problem?
i have installed torch locally
