### ISSUE TITLE
ERROR: ./util/CharSplitLMMinibatchLoader.lua:50: attempt to call method 'split' (a nil value)

### ISSUE THREAD

**Issue by kemaswill** [karpathy/char-rnn#9]
Hi Karpathy,
  I have cloned your code and run the example th train.lua -data_dir data/tinyshakespeare/ -gpuid -1, then get the following error information:

loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
/usr/local/bin/luajit: ./util/CharSplitLMMinibatchLoader.lua:50: attempt to call method 'split' (a nil value)
stack traceback:
	./util/CharSplitLMMinibatchLoader.lua:50: in function 'create'
	train.lua:74: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:129: in main chunk
	[C]: at 0x010cddb820

I'm not familiar with LUA now, so could you check the code to see if there is any bug? Thanks a lot. By the way, I'm running the code using mac os.

Cheers
Junwei Pan

**Comment by marcbelmont** [comment]
I'm having the same issue. I'm using an AWS g2.2xlarge with the following AMI
ipythonnotebook-caffe-theano-pylearn2-torch7-cuda6.5-ubuntu14.04-gpu (ami-813110b1)

**Comment by soumith** [comment]
@marcbelmont that torch install is out of date. Once you are in that AMI, update the torch package (for starters, I do not know what others are out of date).

luarocks install torch
luarocks install cutorch
luarocks install nn
luarocks install cunn

**Comment by marcbelmont** [comment]
@soumith 
Thanks. It now works.
