### ISSUE TITLE
Only copy the state of top_h?

### ISSUE THREAD

**Issue by ffmpbgrnn** [karpathy/char-rnn#91]
Hi, in [train.lua#L276](https://github.com/karpathy/char-rnn/blob/master/train.lua#L276), I found the code only copy the `top_h` to the next batches. Why you didn't copy other `h`s to the next batch?

Thank you!

**Comment by karpathy** [comment]
the state of the RNN is summarized in that last set of states, the other states are not necessary once we've performed a backward pass on that batch. We use that last state to "initialize" the state for next batch in sequence.

**Comment by ffmpbgrnn** [comment]
Thank you, I get it!
