### ISSUE TITLE
newline character in prime text

### ISSUE THREAD

**Issue by codehive** [karpathy/char-rnn#98]
How do I specify new line character in seed text?

**Comment by karpathy** [comment]
`\n` ?

**Comment by codehive** [comment]
-primetext "heyy\n" 
 like this ?

**Comment by codehive** [comment]
th sample.lua cv/lm_lstm_epoch2.14_1.0811.t7 -gpuid -1 -primetext "MAIL_START\nHi" 
creating an lstm...	
seeding with MAIL_START\nHi	
--------------------------	
MAIL_START\nHine Zarked,

==================
