### ISSUE TITLE
Where I sholud put the download codes?

### ISSUE THREAD

**Issue by narrowview** [karpathy/char-rnn#99]
I have installed Torch.And when I run the  commond"$ th train.lua -data_dir data/some_folder -gpuid -1",it shows "cannot open train.lua:No such file or directory".

**Comment by karpathy** [comment]
It sounds like you are new to Linux. You have to `cd` into the directory that contains the script.

**Comment by narrowview** [comment]
Thanks

**Comment by jamie083146** [comment]
Hi, I'd like to ask if you have solved this issue? I faced the same question, but I have cd into the directory which contains the script, and I still got that.....
If you have convent the dataset from .txt to .t7, please tell me how to do this ,please~ 
New to Linux too, THX~

**Comment by narrowview** [comment]
I just cd  into the directory and the train.lua is there.Then run the giving code.
The problem is solved.That's all.Sorry,it seems much later.
